### ISSUE TITLE
Nice to have: debug toolbar with nginx proxy

### ISSUE THREAD

**Issue by ArturLange** [Pylons/pyramid_debugtoolbar#234]
It would be very nice to be able to set up a nginx proxy and serve debug_toolbar there.
When doing something like that:
``` nginx
server {
	listen 1235;
	location / {
		proxy_pass http://127.0.0.1:1234;
	}
}
```
At `127.0.0.1:1235/_debug_toolbar` I get a no style debug toolbar view which doesn't work because it's still making requests on 1234

Maybe there's a way to do that which I don't get?

**Comment by bertjwregeer** [comment]
You'll need some sort of middleware that changes the WSGI environment so that the correct port is presented to the application so that when URL's are created/rendered it contains the correct port number.

**Comment by mmerickel** [comment]
Yes this is entirely possible to setup. It's a misconfiguration between nginx and your application with regards to the ports. Please see http://docs.pylonsproject.org/projects/waitress/en/latest/#using-behind-a-reverse-proxy for some options on how to solve this. The issue is not related to the toolbar itself.
