### ISSUE TITLE
nginx proxy with gunicorn

### ISSUE THREAD

**Issue by jakoandras** [Pylons/pyramid_debugtoolbar#351]
Using gunicorn listening on a unix domain socket behind an nginx proxy, gunicorn sets REMOTE_ADDR to the empty string. So I get the warning [pyramid_debugtoolbar has detected a broken proxy](https://github.com/Pylons/pyramid_debugtoolbar/blob/master/src/pyramid_debugtoolbar/toolbar.py#L207), and debugtoolbar does not work. As far as I understand you assume that REMOTE_ADDR should contain the furthest client's (e.g. the browser's) address, while gunicorn developers think REMOTE_ADDR should be set to the nearest client's (e.g. the other end of the data stream connection terminated by gunicorn) address, and of course there's no IP address associated to a unix domain socket.

I simply set `client_addr = request.client_addr` in toolbar.py as a workaround, but is there a better way to make it work without modifying pyramid_debugtoolbar source?

**Comment by mmerickel** [comment]
REMOTE_ADDR is always intended to be the ip address of the "real" client. The issue is that most of the time the server is not configured to deal with proxy headers and so it does not know who the real client is, it only knows the client directly connected to it (the unix socket for example).

A server (nginx, gunicorn, etc) cannot translate proxy headers into REMOTE_ADDR directly without configuration to tell it which ones are trusted and supported by the upstream proxy (for example `x-real-ip` or `x-forwarded-for`). Also, very often, a server will send those headers through untouched, meaning that malicious clients can set their own values for the headers and now `request.client_addr` will be spoofed. This is the same issue with all proxy headers, including `x-forwarded-proto` for telling the downstream wsgi app that the original request was https or http.

The right answer here is to properly translate the x-forwarded headers that are set by your proxy into their "trusted" equivalents in the wsgi environment. By trusted here, I mean REMOTE_ADDR, wsgi.url_scheme, SERVER_HOST, SERVER_PORT are not http headers, they are keys in the environ that cannot be spoofed by a user unless you take other values and put them in there.

Gunicorn has support for translating most of these headers already. See http://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips and http://docs.gunicorn.org/en/stable/settings.html#secure-scheme-headers

**Comment by jakoandras** [comment]
Thanks, I understand your point of view, non-HTTP-header wsgi environment can generally be trusted more. However please also consider the following:

The specifications state that REMOTE_ADDR should not contain the "real" client's address but the nearest one. The [wsgi specification](https://www.python.org/dev/peps/pep-3333/) does not say anything about this, it references [draft-coar-cgi-v11-03](https://tools.ietf.org/html/draft-coar-cgi-v11-03). draft-coar-cgi-v11-03 does not make it clear either, but its final version, [CGI v1.1 RFC](https://tools.ietf.org/html/rfc3875) says:

"Script authors should be aware that the REMOTE_ADDR and REMOTE_HOST meta-variables (see sections 4.1.8 and 4.1.9) may not identify the ultimate source of the request.  They identify the client for the immediate request to the server; that client may be a proxy, gateway, or other intermediary acting on behalf of the actual source client."

So there seems to be no way to gather the "real" clinet's address from non-HTTP-header wsgi environment, at least when one follows the specification and also uses a reverse proxy in front of the wsgi server. But in this - I guess typical - scenario, HTTP headers can be made just as trusted as the other wsgi environment variables.

Considering Pyramid's "not getting in your way" philosophy, or [Defending Pyramid's Design](https://docs.pylonsproject.org/projects/pyramid/en/latest/designdefense.html), stating 'Pyramid is, for better or worse, a "TIMTOWTDI" system.', I think it would be nice to have a choice in pyramid_debugtoolbar to use some other source for IP based authorization than REMOTE_ADDR.

**Comment by bertjwregeer** [comment]
@jakoandras I added that protection into debug toolbar because people were accidentally exposing themselves and allowing remote access to debug toolbar means you give people free remote code execution.

Unfortunately PEP3333 doesn't specify anything at all regarding hosting WSGI applications using local unix sockets... which also don't have a `SERVER_PORT` or a `SERVER_HOSTNAME` both used to set up the WSGI environ too... so when implementers allow for unix sockets for proxying the standards are already incredibly weak. It's part of the reason why Waitress just recently got a whole bunch of new proxy handling code so that the WSGI environment at least makes some sense even when using unix sockets.

That being said:

debug toolbar also supports a method to allow you to control access:

> Since version 1.0.5 pyramid_debugtoolbar offers custom authorization mechanism to control toolbar feature on per-request basis. Using the config.set_debugtoolbar_request_authorization(callback) directive, you can specify your own function to control whether toolbar functionality is enabled or not.

https://docs.pylonsproject.org/projects/pyramid_debugtoolbar/en/latest/#custom-authorization

You will still get the warning about `REMOTE_ADDR` being set to an invalid value but with the custom authorization you can still get the debug toolbar to display even in those cases, and you are on the hook for making sure you don't accidentally expose the debug toolbar to the wrong people.

**Comment by jakoandras** [comment]
Thanks! That should solve my problem.

It seems to me that there's a bug here. I get the warning on this [`elif`](https://github.com/Pylons/pyramid_debugtoolbar/blob/master/src/pyramid_debugtoolbar/toolbar.py#L205) suite, so `client_addr` remained `None`, and that's why the next [`if`](https://github.com/Pylons/pyramid_debugtoolbar/blob/master/src/pyramid_debugtoolbar/toolbar.py#L217) stops debugtoolbar from showing up, no matter what `auth_check(request)` would return.
